config/routes.rb
First_Website::Application.routes.draw do
  resources :authentications

  devise_for :users, :controllers => { :registrations => 'registrations' }
  

  root to: 'static_pages#home'

  resources :skills do 
    get :autocomplete_skilllabel_label, :on => :collection
  end
  resources :experiences
  resources :references
  resources :postings
  resources :projects
  resources :links
  resources :profile
  resources :surveys
  resources :friendships
  resources :messages
  resources :friendships

  match '/search', to: 'search#search', via: 'get'
  match '/findfriend', to: 'friendships#findfriend', via: 'get'
  match '/results', to: 'surveys#add', via: 'post'
  match '/reccomended', to: 'skills#reccomend', via:'get'
  match '/details', to: 'experiences#details', via: 'get'
  match '/one_ref', to: 'references#one_ref', via: 'get'
  match '/add_exp', to: "experiences#add", via: 'get'
    
  match '/auth/:provider/callback', to: 'authentications#create', via: 'get'
  resources :authentications

  get  'addfriend', to: 'friendships#addfriend'
  post  'addfriend', to: 'friendships#addfriend'
  get  'accept', to: 'friendships#accept'
  get  'decline', to: 'friendships#decline'
  get 'network', to: 'friendships#index'
  get 'privatechat', to: 'messages#privatechat'
  get 'storemsg', to: 'messages#storemsg'

  

  

  

end

app/models/skill.rb
class Skill < ActiveRecord::Base

        belongs_to :user
        
        validates :user_id, :skill_id, presence: true
        validates_inclusion_of :mandatory, :if => :posting_id?, :in => [true, false]

        validates :label, presence: true
 	after_create :do_setID

  private
    def do_setID
      
      newID = self.id
      self.update_attributes(:skill_id => newID)
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  autocomplete :skilllabel, :label, :full => true

  def index
  	@skill = Skill.new
    @user = current_user
    @userID = current_user.user_id
    @skills = Skill.where(:user_id => current_user.user_id).paginate(page: params[:page])
  end

  def show

    @skill = Skill.find(params[:id])
    @user = current_user

  end

  def destroy
    @skill = Skill.find(params[:id])
    if (user_signed_in? && current_user.user_id == @skill.user_id)
      @skill.destroy
      flash[:success] = "Skill Removed."
    else
      flash[:error] = "No access"
    end
    redirect_to '/skills'

  end

  def reccomend
    @user = current_user
    if @user.employer?
    else
      @userskills = Skill.where(user_id: @user.user_id)
      @postings = find_postings(@userskills)
      @postings = sort_postings(@postings)
    end

    
    
  end

  def create
  	if(user_signed_in?)
  		@skill = Skill.new(skill_params)
      @skill.user_id = current_user.user_id
      if(Skilllabel.find_by(label: @skill.label).nil?)
        @skilllabel = Skilllabel.new
        @skilllabel.label = @skill.label
        @skilllabel.save
      end
  		if(@skill.save)
  			flash[:success] = "Skill created!"
      	redirect_to "/skills"
      else
  			flash[:error] = "Fill in all required fields"
       	redirect_to "/skills"
      end
      @skills = Skill.where(:user_id => current_user.user_id).paginate(page: params[:page])
      @userID = current_user.user_id
  	else
  		flash[:error] = "No access"
      redirect_to root_path
    end
  end

  private
    def find_postings(userskills)
      postings = Posting.where(posting_id: 0)
      p userskills
      userskills.each do |us|
        @label = us.label
        @jobskills = Skill.where(label: @label)
        @jobskills.each do |js|
          if !js.posting_id.nil?
            postings.push(Posting.find_by(posting_id: js.posting_id))
          end
        end
      end
      p postings
      return postings
    end

    def sort_postings(postings)
      @hash = {0 => 0}
      postings.each do |p|
        if @hash[p.posting_id].nil?
          @hash.merge!({p.posting_id => 1})
        else
          @hash[p.posting_id] = @hash[p.posting_id] + 1
        end
      end
      postings.clear
      @hash = Hash[@hash.sort_by{|k, v| v}.reverse]
      @hash.each_key do |key|
        postings.push(Posting.find_by(posting_id: key))
      end
      return postings
    end

    def skill_params
        params.require(:skill).permit(:label, :posting_id, :skill_id, :mandatory)
    end
end

app/views/skills/edit.html.erb
<h1>Edit this Skill</h1>

<%= simple_form_for @skill, :html => { :method => :put} do |f| %>

  <p> Fields marked with * are required </p>
  
  <div><%= f.label "Title *" %> 
  E.g. "Programming with Java" <br />
  <%= f.autocomplete_field :label, autocomplete_skill_label_skills_path, :default => @skill.label%></div>

  <div>
  	<%= f.label "Description *" %>
    <%= f.text_area :description, :autofocus => true , :default => @skill.description %>
  </div>

 <%= f.submit "Submit", class: "btn btn-large btn-primary" %>

<% end %>

app/views/skills/index.html.erb
<h1> Add a Skill</h1>


<div class = "row" height = 30px style = "padding-left: 1.5em;">
  <div class = "col-lg-2" style ="" ></div>
    <div class = "col-lg-8" style ="" >
        <%= simple_form_for @skill, :url => { :action => "create" } do |f| %>
        <div> 
          <%= f.autocomplete_field :label, autocomplete_skilllabel_label_skills_path, :default => @skill.label, :autofocus => true%>
        </div>
        <% if @user.employer? %>
          <div>
            <%= f.hidden_field :posting_id, :value => @postID %>
          </div>
          <div>
            <%= f.input :mandatory, collection: [['Mandatory', true], ['Optional',false]], :default => 1%>
          </div>
        <% end %>
        <%= f.submit "Submit",:label => "Submit", class: "btn btn-large btn-primary" %>
    </div>
  </div>

<% end %>

  <div class = "row" height = 30px style = "">
    <div class = "col-lg-2" style ="" ></div>
      <div class = "col-lg-8" style ="" >
      	<% if !@skills.nil? %>
          <h1>All Skills</h1>
      		<%= render partial: 'shared/skills', collection: @skills %>
      	<% end %>
      </div>
    </div>

app/views/skills/reccomend.html.erb
 <% if !@postings.nil? %>
    <h1>All Postings</h1>
    <%= render partial: 'shared/postings', collection: @postings %>
  <% end %>

app/views/skills/show.html.erb
<h1> <%= @skill.label %> </h1>
        
    <h2><%= @skill.description %> </h2>