config/routes.rb
First_Website::Application.routes.draw do
  resources :authentications

  devise_for :users, :controllers => { :registrations => 'registrations' }
  

  root to: 'static_pages#home'

  resources :skills do 
    get :autocomplete_skilllabel_label, :on => :collection
  end
  resources :experiences
  resources :references
  resources :postings
  resources :projects
  resources :links
  resources :profile
  resources :surveys
  resources :friendships
  resources :messages
  resources :friendships

  match '/search', to: 'search#search', via: 'get'
  match '/findfriend', to: 'friendships#findfriend', via: 'get'
  match '/results', to: 'surveys#add', via: 'post'
  match '/reccomended', to: 'skills#reccomend', via:'get'
  match '/details', to: 'experiences#details', via: 'get'
  match '/one_ref', to: 'references#one_ref', via: 'get'
  match '/add_exp', to: "experiences#add", via: 'get'
    
  match '/auth/:provider/callback', to: 'authentications#create', via: 'get'
  resources :authentications

  get  'addfriend', to: 'friendships#addfriend'
  post  'addfriend', to: 'friendships#addfriend'
  get  'accept', to: 'friendships#accept'
  get  'decline', to: 'friendships#decline'
  get 'network', to: 'friendships#index'
  get 'privatechat', to: 'messages#privatechat'
  get 'storemsg', to: 'messages#storemsg'

  

  

  

end

app/views/shared/_experiences.html.erb
<head>
    <style = "text/css">
      .picholder{
        width: 6em;
      }

    </style>

</head>
  <body>
    <div class = "row" height = 30px style = "padding-left: 1.5em;">
      <div class = "col-lg-12" style ="" >
        <table border = 0 style ="margin: 2em">
          <tr>
            <td class = "picholder"> this is where the picture goes </td>
            <td style = "width: 50em"><p>
              <%= link_to experiences.title, {:controller => "experiences", :action => "details", :id => experiences.experience_id}, :id => "more"%></p>
              <p><%= experiences.description %></p>
            </td>
          </tr>
            <% if !experiences.nil? %>
              <% if experiences.user_id == @userID %>
              <tr>
                <td></td>
                <td>
                  <table>
                    <tr>
                      <td>
                        <div class = "hover">
                          <%= link_to image_tag('edit.png'), edit_experience_path(experiences.experience_id), class: "btn btn-small btn-info"%>
                          <div class = "tooltip">
                            Click here to edit
                           </div>
                       </div>
                     </td>
                     <td>
                      <div class = "hover">
                          <%= link_to image_tag('delete.png'), experiences, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-small btn-danger" %>
                          <div class = "tooltip">
                            Click here to delete
                           </div>
                       </div>
                     </td>

                     <td>

                      <div class = "hover">
                         <%= link_to image_tag('pencil.png'), projects_path(:expID => experiences.experience_id), class: "btn btn-small btn-primary" %>

                          <div class = "tooltip">
                            Click here to add a project
                           </div>
                       </div>
                     </td>
                   </tr>
                 </table>
                </td>
                <% end %>
              <% end %>
            </tr>
        </table>
      </div>
    </div>
  </body>

app/views/shared/_findfriend.html.erb
<% @friend =findfriend %>
<% if user_signed_in? && @user.user_id != @friend.user_id %>
<%= link_to @friend.fname+" "+@friend.lname, profile_path(@friend) %>

      <%= link_to "+Add friend", {:controller => "friendships", :action => 'addfriend', :sender => @user.user_id, :receiver => @friend.user_id}, class: "btn btn-small btn-primary"%>

<% end %>

app/views/shared/_friendsaccepted.html.erb
<% @friend = User.find_by(user_id: friendsaccepted.sender_id) %>

<div class = "row" height = 30px style = "margin-bottom: 10em;">
	<div class = "col-lg-1">
		<%= image_tag('prof.jpeg', :class => "minipic") %>
	</div>
  <div class = "col-lg-2" style ="" >
	<%= link_to @friend.fname+" "+@friend.lname, profile_path(@friend) %> 
	</div>
	<div class = "col-lg-8" style ="" >
		<div class = "hover">
			<%= link_to image_tag('delete.png'), friendsaccepted, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-small btn-danger" %>
			<div class = "tooltip">
				Click to remove friend
			</div>
		</div>
	</div>
</div>

app/views/shared/_friendsadded.html.erb
<% @friend = User.find_by(user_id: friendsadded.receiver_id) %>



<div class = "row" height = 30px style = "margin-bottom: 10em">
	<div class = "col-lg-1">
		<%= image_tag('prof.jpeg', :class => "minipic") %>
	</div>
  <div class = "col-lg-2" style ="" >
	<%= link_to @friend.fname+" "+@friend.lname, profile_path(@friend) %> 
	</div>
	<div class = "col-lg-8" style ="" >
		<div class = "hover">
			<%= link_to image_tag('delete.png'), friendsadded, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-small btn-danger" %>
			<div class = "tooltip">
				Click to remove friend
			</div>
		</div>
	</div>
</div>

app/views/shared/_mini_requirements.html.erb
	<% if mini_requirements.mandatory %>
		This requirement is mandatory
	<% else %>
		This requirement is optional
	<%end%>
	<br>
	 <%= mini_requirements.description %>
	<br>
	 A <%= mini_requirements.degree %> is required
	 <br>
	 <%= mini_requirements.educationLvl %> is required
	 <br>
	  A minimum of <%= mini_requirements.exp %> experience is needed
	  <br>
	  in the field of <%= mini_requirements.exp_area %>

app/views/shared/_newmessages.html.erb
<%= link_to "New Message(s) from "+ newmessages.sender_name, {controller: "messages", action: "privatechat", id1: @user.user_id, id2: @friend.user_id} %>
</p>

app/views/shared/_profileexperiences.html.erb
<head>
</head>
  <body>
    <table>
      <tr>
        <td ><p style ="font-weight:bold;font-size:24px"><%= link_to profileexperiences.title, experience_path(profileexperiences), :style => "color:black;" %></p></td>
      </tr>
      <tr>
        <td>
        <table>
          <tr>
        <td style = "max-width:12em"><p><%= profileexperiences.company_name %></p></td><tr><tr>
         <td style = "max-width:12em"><p><%= profileexperiences.sdate.strftime("%b-%d-%Y") %> &nbsp-&nbsp </p></td>
         <% if !profileexperiences.fdate.nil? %>
          <td style = "max-width:12em"><p><%= profileexperiences.fdate.strftime("%b-%d-%Y") %></p></td>
          <% else %>
          <td style = "max-width:12em"><p>present</p></td>
        <% end %>
      </tr>
    </table>
  </td>
      </tr>
    </table>

    <% @projects = Project.where(:experience_id => profileexperiences.experience_id).paginate(page: params[:page]) %>

    <% if !@projects.empty? %>
    <p style = "font-weight:bold;">Projects linked to this experience</p>
    <%= render partial: 'shared/profileprojects', collection: @projects %>
    <% end %>
 </body>

app/views/shared/_profilelinks.html.erb
<head>
</head>
  <body>
    <table>
      <tr>
 		<td></td>
 		<% if profilelinks.is_image == true %>
        <td style = "max-width:12em"><p> <%= image_tag(profilelinks.url) %></p></td>
        <% else %>
        <td style = "max-width:12em"><p><a href = <%=profilelinks.url%> target = "_blank" ><%=profilelinks.url%></a></p></td>
        <% end %>
      </tr>
    </table>
 </body>

app/views/shared/_profilepostings.html.erb
<style type="text/css">
    
    .tab_header2{
      background: #70B8FF; 
      width: 12em; 
      height: 2em;
      border-top-left-radius:12px; 
      border-top-right-radius:36px; 
      position: relative;
      text-align: left;
      /*font-weight: bold;*/
      font-size: 16px;
      padding-top: 2px;
      padding-right: 2px;
      padding-left: 10px;
      margin-right: 2px;
    }

    .salary{
      background: #70B8FF; 
      width: 12.4em; 
      height: 2em;
      border-top-left-radius:12px; 
      border-top-right-radius:10px; 
      position: relative;
      text-align: left;
      /*font-weight: bold;*/
      font-size: 16px;
      padding-top: 2px;
      padding-right: 2px;
      padding-left: 10px;
      margin-right: 2px;
    }

    .content2{
       border: solid #3399FF 2px;
       position: relative; 
       top: -2.5em; 
       height: 5em;
       background: white;
       line-height: 20px;
       padding-left: 5px;
       min-width: 10em;
       max-width: 30em;
       max-height: 15em;
       overflow: scroll;
    }
  </style>

<div class = "row">
    <div class = "col-lg-6">

        <div class = "tab_header2" style = "background: #3399FF">
          <% if !profilepostings.title.nil? %>
            <%= profilepostings.title%>
            <%end%>
        </div>

        <div class = "salary" style = "left: 12em; top: -2em;" >
          <% if !profilepostings.salary.nil? %>
            $<%= profilepostings.salary%>
            <%end%>
        </div>
        <div class = "content2" style = "">
          <% if !profilepostings.description.nil? %>
            <%= profilepostings.description%>
            <%end%>
        </div>

    </div>

     <div class = "col-lg-6">

        <div class = "tab_header2" style = "top: 0em; background: #3399FF; width: 9em">
            Skills Needed
        </div>

        <div class = "content2" style = "top: 0em">
            <% @array = @skills.to_a %>
          <% if(@array.empty?) %>
            No specific Skills are needed for this job
          <%else%>
            <% finish = 3 %>
            <% for i in 0..finish%>
              <% if(i < @array.length) %>
              <p>
                <%= @array[i].mandatory %> : <%= @array[i].label %> 
              </p>
              <%end%>
            <%end%>
            <% if @array.length > finish + 1 %>
              </br>
              </br>
              <%= link_to "More",skills_path, :id => "more"%>
            <% end %>
          <%end%>
        </div>
    </div>
</div>

app/views/shared/_profileprojects.html.erb
<head>
</head>
  <body>
    <p><%= link_to profileprojects.name, project_path(profileprojects), :style => "color:black;"%> </p>
 </body>

app/views/shared/_profilereferences.html.erb
<head>
</head>
  <body>
    <table>
      <tr>
        <table>
          <tr>
            <td><p><%= profilereferences.fname %></p></td>
            <td><p><%= profilereferences.lname %></p></td>
          </tr>
        </table>
      </tr>
      <tr>
        <td style = "max-width:12em"><p><%= profilereferences.relationship %></p></td>
      </tr>
      <tr>
        <% if !profilereferences.email.nil? %>
          <td style = "max-width:12em"><p><%= profilereferences.email %></p></td>
        <% else %>
          <td style = "max-width:12em"></td>
        <% end %>
      </tr>
      <tr>
        <% if !profilereferences.phone_number.nil? %>
          <td style = "max-width:12em"><p><%= number_to_phone(profilereferences.phone_number) %></p></td>
        <% else %>
          <td style = "max-width:12em"></td>
        <% end %>
      </tr>
      <tr>
        <% if !profilereferences.yrsknown.nil? %>
          <td style = "max-width:12em"><p>Known for <%= profilereferences.yrsknown %> years</p></td>
        <% else %>
          <td style = "max-width:12em"></td>
        <% end %>
      </tr>
    </table>
 </body>

app/views/shared/_projects.html.erb
<head>
</head>
  <body>
    <table>
      <tr>
 		<td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
        <td style = "max-width:12em"><p>Name: <%= projects.name %></p></td>
        <tr></tr>
        <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
        <td style = "max-width:12em"><p>Description: <%= projects.description %></p></td>

         <td><%= link_to "Edit this Project", edit_project_path(projects.id), class: "btn btn-small btn-info"%></td>
        <td><%= link_to "Delete this Project", projects, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-small btn-danger" %></td>
        <td><%= link_to "Add a Link", links_path(:projID => projects.project_id), class: "btn btn-small btn-primary" %></td>
       
    </table>

    <% @links = Link.where(:project_id => projects.project_id).paginate(page: params[:page]) %>

    <% if !@links.empty? %>
    <p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Links for this Project</p>
    <%= render partial: 'shared/links', collection: @links %>
    <% end %>
 </body>

app/views/shared/_references.html.erb
<head>
</head>
  <body>
    <table>
      <tr>
        <td style = "width:12em"><p><%= references.fname %></p></td>
        <td style = "width:12em"><p><%= references.lname %></p></td>
        <td style = "width:12em"></td>
        <% if !references.nil? %>
          <% if references.user_id == @userID %>
            <td><%= link_to "Edit this Reference", edit_reference_path(references.id), class: "btn btn-small btn-info"%></td>
            <td><%= link_to "Delete this Reference", references, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-small btn-danger" %></td>
            <% end %>
          <% end %>
      </tr>
      <tr>
        <td style = "width:12em"><p><%= references.relationship %></p></td>
      </tr>
      <tr>
        <% if !references.email.nil? %>
          <td style = "width:12em"><p><%= references.email %></p></td>
        <% else %>
          <td style = "width:12em"></td>
        <% end %>
        <% if !references.phone_number.nil? %>
          <td style = "width:12em"><p><%= number_to_phone(references.phone_number) %></p></td>
        <% else %>
          <td style = "width:12em"></td>
        <% end %>
        <% if !references.yrsknown.nil? %>
          <td style = "width:12em"><p>Known for <%= references.yrsknown %> years</p></td>
        <% else %>
          <td style = "width:12em"></td>
        <% end %>
      </tr>
    </table>
 </body>

app/views/shared/_skills.html.erb
<head>

  <style = "text/css">
    .space{
      padding: 0.5em;
    }

  </style>
</head>
  <body>
    <table border = "0">
      <tr>
        <td class = "space" style = "max-width:12em; width: 12em"><p><%= skills.label %></p></td>
        <% if !skills.nil? %>
          <% if skills.user_id == @userID %>
            <td class = "space">
              <div class = "hover">
                <%= link_to image_tag('edit.png'), edit_skill_path(skills.skill_id), class: "btn btn-small btn-info"%>
              <div class = "tooltip">
                Click here to edit
              </div>
            </div>
            </td>
            <td class = "space">
              <div class = "hover">
                <%= link_to image_tag('delete.png'), skills, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-small btn-danger" %>
              <div class = "tooltip">
                Click here to delete
              </div>
            </div>
            </td>
            <% end %>
          <% end %>
      </tr>
    </table>
 </body>